#!/usr/bin/env python3
"""
Generate apps/mobile/lib/locationData.ts from the spreadsheet + expansion data.
Run from repo root: python3 scripts/gen_location_data.py
"""

import openpyxl
import re
import json
from pathlib import Path

XLSX = Path(__file__).parent.parent / "Geo Location" / "travel_geo_tag_database_1000 copy.xlsx"
OUT  = Path(__file__).parent.parent / "apps/mobile/lib/locationData.ts"

# ── Geo tag inference ─────────────────────────────────────────────────────────

KEYWORD_TAGS = {
    "beach":      ["coast","beach","riviera","bay","caye","cabo","playa","lido","litoral","shoreline","seashore","balnear"],
    "mountain":   ["mountain","alp","alps","highland","peak","summit","sierra","cordillera","himalaya","massif","range","ridge","plateau","tableland","altiplano","mt ","mt."],
    "lake":       ["lake","fjord","loch","lagoon","laguna","dam","reservoir"],
    "forest":     ["forest","wood","rainforest","jungle","amazon","woodland","grove","taiga"],
    "desert":     ["desert","sahara","wadi","atacama","namib","gobi","dryland","arid","steppe"],
    "island":     ["island","isle","archipelago","atoll","isola","isla","isles","insulae","key","keys","caye"],
    "tropical":   ["tropical","reef","mangrove","rainforest"],
    "arctic":     ["arctic","polar","tundra","glacier","ice field","snowfield","lapland"],
    "countryside":["valley","plain","countryside","rural","vineyard","wine region","winery","farmland","plains","prairie","pampa","savanna","savannah","wetland","wetlands","delta","lowland"],
    "city":       [],  # applied via destination_type
}

# country → forced tags (all entries in that country get these)
COUNTRY_TAGS: dict[str, list[str]] = {
    # Tropical
    "Thailand":               ["tropical","beach"],
    "Vietnam":                ["tropical","beach"],
    "Indonesia":              ["tropical","beach","island"],
    "Philippines":            ["tropical","beach","island"],
    "Malaysia":               ["tropical","beach"],
    "Cambodia":               ["tropical"],
    "Laos":                   ["tropical"],
    "Myanmar":                ["tropical"],
    "Singapore":              ["tropical","city"],
    "Costa Rica":             ["tropical","beach","forest"],
    "Panama":                 ["tropical","beach"],
    "Belize":                 ["tropical","beach"],
    "Cuba":                   ["tropical","beach","island"],
    "Jamaica":                ["tropical","beach","island"],
    "Dominican Republic":     ["tropical","beach","island"],
    "Barbados":               ["tropical","beach","island"],
    "Saint Lucia":            ["tropical","beach","island"],
    "Grenada":                ["tropical","beach","island"],
    "Antigua and Barbuda":    ["tropical","beach","island"],
    "Aruba":                  ["beach","island"],
    "Curacao":                ["beach","island"],
    "Fiji":                   ["tropical","beach","island"],
    "Vanuatu":                ["tropical","beach","island"],
    "Samoa":                  ["tropical","beach","island"],
    "Tonga":                  ["tropical","beach","island"],
    "Papua New Guinea":       ["tropical","forest","island"],
    "Solomon Islands":        ["tropical","beach","island"],
    "French Polynesia":       ["tropical","beach","island"],
    "Cook Islands":           ["tropical","beach","island"],
    "Palau":                  ["tropical","beach","island"],
    "Maldives":               ["tropical","beach","island"],
    "Seychelles":             ["tropical","beach","island"],
    "Mauritius":              ["tropical","beach","island"],
    "Reunion":                ["tropical","beach","island","mountain"],
    "Madagascar":             ["tropical","beach","island"],
    "Rwanda":                 ["tropical","mountain","forest"],
    "Uganda":                 ["tropical","forest"],
    "Ghana":                  ["tropical","beach"],
    "Senegal":                ["tropical","beach"],
    "Mozambique":             ["tropical","beach"],
    "Tanzania":               ["beach","mountain"],
    "Sri Lanka":              ["tropical","beach","mountain"],
    "Brazil":                 ["tropical","beach","forest"],
    "Colombia":               ["tropical","beach","mountain"],
    "Ecuador":                ["tropical","mountain"],
    "Guatemala":              ["tropical","mountain"],
    "Bhutan":                 ["mountain"],
    # Arctic / cold
    "Iceland":                ["arctic","mountain"],
    "Norway":                 ["mountain","arctic","forest","lake"],
    "Finland":                ["forest","lake","arctic"],
    "Sweden":                 ["forest","lake"],
    "Greenland":              ["arctic","mountain"],
    # Mountain
    "Nepal":                  ["mountain"],
    "Kyrgyzstan":             ["mountain"],
    "Bolivia":                ["mountain","countryside"],
    "Peru":                   ["mountain","countryside"],
    "Kazakhstan":             ["mountain","desert","countryside"],
    "Armenia":                ["mountain","countryside","city"],
    "Georgia":                ["mountain","countryside","city"],
    "Azerbaijan":             ["mountain","beach","city"],
    # Desert
    "Egypt":                  ["desert","beach","city"],
    "Namibia":                ["desert","countryside"],
    "Jordan":                 ["desert","mountain","city"],
    "Oman":                   ["desert","mountain","beach"],
    "Saudi Arabia":           ["desert","city"],
    "United Arab Emirates":   ["desert","city","beach"],
    "Qatar":                  ["desert","city","beach"],
    "Bahrain":                ["island","beach","city"],
    # Beach countries
    "Cape Verde":             ["beach","island"],
    "Bahamas":                ["beach","island","tropical"],
    "Trinidad and Tobago":    ["beach","island","tropical"],
    # Broad multi-tag
    "France":                 ["city","beach","mountain","countryside","forest"],
    "Spain":                  ["city","beach","mountain","countryside"],
    "Italy":                  ["city","beach","mountain","countryside"],
    "Greece":                 ["city","beach","island"],
    "Portugal":               ["city","beach","mountain","countryside"],
    "Switzerland":            ["mountain","lake","city"],
    "Austria":                ["mountain","lake","city","countryside","forest"],
    "Croatia":                ["beach","island","city"],
    "Montenegro":             ["beach","mountain"],
    "Germany":                ["city","forest","countryside","mountain"],
    "Netherlands":            ["city","countryside"],
    "Belgium":                ["city","countryside"],
    "Denmark":                ["city","beach"],
    "Poland":                 ["city","countryside","forest"],
    "Czech Republic":         ["city","countryside","forest"],
    "Czechia":                ["city","countryside","forest"],
    "Hungary":                ["city","countryside","lake"],
    "Romania":                ["mountain","countryside","city","forest"],
    "Bulgaria":               ["mountain","beach","city"],
    "Serbia":                 ["city","countryside"],
    "Albania":                ["beach","mountain","city"],
    "Slovenia":               ["mountain","lake","countryside","forest"],
    "Slovakia":               ["mountain","countryside","city"],
    "Bosnia and Herzegovina": ["mountain","city","countryside"],
    "North Macedonia":        ["mountain","lake","city"],
    "Lithuania":              ["city","countryside","forest","beach"],
    "Latvia":                 ["city","countryside","forest","beach"],
    "Estonia":                ["city","countryside","forest","beach"],
    "Ireland":                ["city","countryside","beach"],
    "United Kingdom":         ["city","countryside","mountain","beach","forest"],
    "Luxembourg":             ["city","countryside"],
    "Malta":                  ["beach","island","city"],
    "Cyprus":                 ["beach","island","city","mountain"],
    "USA":                    ["city","beach","mountain","countryside","desert","forest"],
    "United States":          ["city","beach","mountain","countryside","desert","forest"],
    "Canada":                 ["mountain","forest","lake","arctic","city"],
    "Mexico":                 ["beach","city","countryside","tropical"],
    "Argentina":              ["mountain","countryside","city","beach"],
    "Chile":                  ["mountain","beach","desert","countryside"],
    "Uruguay":                ["beach","countryside"],
    "Paraguay":               ["countryside"],
    "Venezuela":              ["beach","tropical","mountain"],
    "Guyana":                 ["tropical","forest"],
    "Japan":                  ["mountain","city","forest","countryside"],
    "South Korea":            ["city","mountain"],
    "Taiwan":                 ["mountain","city","beach"],
    "China":                  ["city","mountain","countryside","beach"],
    "Hong Kong":              ["city","beach"],
    "Macau":                  ["city"],
    "Mongolia":               ["countryside","mountain","desert"],
    "India":                  ["beach","mountain","city","desert"],
    "Pakistan":               ["mountain","city"],
    "Morocco":                ["desert","mountain","city","beach"],
    "South Africa":           ["beach","mountain","city","countryside"],
    "Kenya":                  ["mountain","countryside"],
    "Ethiopia":               ["mountain","city"],
    "Zimbabwe":               ["mountain","countryside"],
    "Zambia":                 ["mountain","countryside"],
    "Botswana":               ["countryside","desert"],
    "New Zealand":            ["mountain","beach","countryside","forest"],
    "Australia":              ["beach","city","countryside","desert","mountain"],
    "Turkey":                 ["beach","mountain","city","countryside"],
    "Israel":                 ["beach","city","countryside","desert"],
    "Lebanon":                ["mountain","city","beach"],
    "Uzbekistan":             ["desert","city"],
    "Tunisia":                ["beach","desert","city"],
    "Puerto Rico":            ["beach","island","tropical","city"],
    "Pakistan":               ["mountain","city"],
    "Brunei":                 ["tropical","forest"],
    "Bhutan":                 ["mountain","forest"],
}

def infer_tags(name: str, destination_type: str, country: str) -> list[str]:
    tags: set[str] = set()
    nl = name.lower()

    # keyword-based
    for tag, keywords in KEYWORD_TAGS.items():
        for kw in keywords:
            if kw in nl:
                tags.add(tag)

    # destination_type
    if destination_type == "city":
        tags.add("city")

    # country context
    for ctag in COUNTRY_TAGS.get(country, []):
        tags.add(ctag)

    # ensure cities always get city tag
    if destination_type == "city":
        tags.add("city")

    # If we ended up with nothing, give a sensible default
    if not tags:
        if destination_type == "city":
            tags.add("city")
        else:
            tags.add("countryside")

    return sorted(tags)

# ── Expansion data ────────────────────────────────────────────────────────────
# Additional entries not in the spreadsheet, targeting ~5000 total.
# Each entry: (name, destination_type, country)

EXTRA_ENTRIES = [
    # ── More countries ──
    ("Afghanistan", "country", "Afghanistan"),
    ("Angola", "country", "Angola"),
    ("Bangladesh", "country", "Bangladesh"),
    ("Belarus", "country", "Belarus"),
    ("Benin", "country", "Benin"),
    ("Burkina Faso", "country", "Burkina Faso"),
    ("Burundi", "country", "Burundi"),
    ("Cameroon", "country", "Cameroon"),
    ("Central African Republic", "country", "Central African Republic"),
    ("Chad", "country", "Chad"),
    ("Comoros", "country", "Comoros"),
    ("Congo", "country", "Congo"),
    ("DR Congo", "country", "DR Congo"),
    ("Djibouti", "country", "Djibouti"),
    ("Eritrea", "country", "Eritrea"),
    ("Eswatini", "country", "Eswatini"),
    ("Gabon", "country", "Gabon"),
    ("Gambia", "country", "Gambia"),
    ("Guinea", "country", "Guinea"),
    ("Guinea-Bissau", "country", "Guinea-Bissau"),
    ("Haiti", "country", "Haiti"),
    ("Honduras", "country", "Honduras"),
    ("Iran", "country", "Iran"),
    ("Iraq", "country", "Iraq"),
    ("Ivory Coast", "country", "Ivory Coast"),
    ("Kosovo", "country", "Kosovo"),
    ("Kuwait", "country", "Kuwait"),
    ("Lesotho", "country", "Lesotho"),
    ("Liberia", "country", "Liberia"),
    ("Libya", "country", "Libya"),
    ("Malawi", "country", "Malawi"),
    ("Mali", "country", "Mali"),
    ("Mauritania", "country", "Mauritania"),
    ("Moldova", "country", "Moldova"),
    ("Niger", "country", "Niger"),
    ("Nigeria", "country", "Nigeria"),
    ("Russia", "country", "Russia"),
    ("Sierra Leone", "country", "Sierra Leone"),
    ("Somalia", "country", "Somalia"),
    ("South Sudan", "country", "South Sudan"),
    ("Sudan", "country", "Sudan"),
    ("Syria", "country", "Syria"),
    ("Tajikistan", "country", "Tajikistan"),
    ("Timor-Leste", "country", "Timor-Leste"),
    ("Togo", "country", "Togo"),
    ("Turkmenistan", "country", "Turkmenistan"),
    ("Ukraine", "country", "Ukraine"),
    ("Yemen", "country", "Yemen"),
    ("Micronesia", "country", "Micronesia"),
    ("Marshall Islands", "country", "Marshall Islands"),
    ("Kiribati", "country", "Kiribati"),
    ("Nauru", "country", "Nauru"),
    ("Tuvalu", "country", "Tuvalu"),
    ("El Salvador", "country", "El Salvador"),
    ("Nicaragua", "country", "Nicaragua"),
    ("Ecuador", "country", "Ecuador"),
    ("Suriname", "country", "Suriname"),
    ("Libya", "country", "Libya"),
    ("Algeria", "country", "Algeria"),
    ("Andorra", "country", "Andorra"),
    ("Liechtenstein", "country", "Liechtenstein"),
    ("Monaco", "country", "Monaco"),
    ("San Marino", "country", "San Marino"),
    ("Vatican City", "country", "Vatican City"),
    ("Macao", "country", "Macao"),

    # ── European cities ──
    ("Alicante", "city", "Spain"),
    ("Bilbao", "city", "Spain"),
    ("Cadiz", "city", "Spain"),
    ("Cordoba", "city", "Spain"),
    ("Ibiza Town", "city", "Spain"),
    ("Malaga", "city", "Spain"),
    ("Palma", "city", "Spain"),
    ("San Sebastian", "city", "Spain"),
    ("Tarragona", "city", "Spain"),
    ("Zaragoza", "city", "Spain"),
    ("Bari", "city", "Italy"),
    ("Catania", "city", "Italy"),
    ("Genoa", "city", "Italy"),
    ("Lecce", "city", "Italy"),
    ("Matera", "city", "Italy"),
    ("Palermo", "city", "Italy"),
    ("Perugia", "city", "Italy"),
    ("Pisa", "city", "Italy"),
    ("Siena", "city", "Italy"),
    ("Taormina", "city", "Italy"),
    ("Trieste", "city", "Italy"),
    ("Verona", "city", "Italy"),
    ("Thessaloniki", "city", "Greece"),
    ("Heraklion", "city", "Greece"),
    ("Rhodes Town", "city", "Greece"),
    ("Mykonos Town", "city", "Greece"),
    ("Corfu Town", "city", "Greece"),
    ("Patras", "city", "Greece"),
    ("Chania", "city", "Greece"),
    ("Avignon", "city", "France"),
    ("Biarritz", "city", "France"),
    ("Bordeaux", "city", "France"),
    ("Cannes", "city", "France"),
    ("Chamonix", "city", "France"),
    ("Colmar", "city", "France"),
    ("Dijon", "city", "France"),
    ("La Rochelle", "city", "France"),
    ("Montpellier", "city", "France"),
    ("Nice", "city", "France"),
    ("Rennes", "city", "France"),
    ("Strasbourg", "city", "France"),
    ("Aachen", "city", "Germany"),
    ("Bremen", "city", "Germany"),
    ("Dortmund", "city", "Germany"),
    ("Dresden", "city", "Germany"),
    ("Dusseldorf", "city", "Germany"),
    ("Freiburg", "city", "Germany"),
    ("Heidelberg", "city", "Germany"),
    ("Leipzig", "city", "Germany"),
    ("Lubeck", "city", "Germany"),
    ("Rostock", "city", "Germany"),
    ("Nuremberg", "city", "Germany"),
    ("Braga", "city", "Portugal"),
    ("Coimbra", "city", "Portugal"),
    ("Funchal", "city", "Portugal"),
    ("Lagos", "city", "Portugal"),
    ("Nazare", "city", "Portugal"),
    ("Obidos", "city", "Portugal"),
    ("Sintra", "city", "Portugal"),
    ("Tavira", "city", "Portugal"),
    ("Amsterdam", "city", "Netherlands"),
    ("Rotterdam", "city", "Netherlands"),
    ("The Hague", "city", "Netherlands"),
    ("Utrecht", "city", "Netherlands"),
    ("Maastricht", "city", "Netherlands"),
    ("Eindhoven", "city", "Netherlands"),
    ("Ghent", "city", "Belgium"),
    ("Antwerp", "city", "Belgium"),
    ("Liege", "city", "Belgium"),
    ("Namur", "city", "Belgium"),
    ("Bern", "city", "Switzerland"),
    ("Interlaken", "city", "Switzerland"),
    ("Lausanne", "city", "Switzerland"),
    ("Lucerne", "city", "Switzerland"),
    ("Montreux", "city", "Switzerland"),
    ("St. Moritz", "city", "Switzerland"),
    ("Zermatt", "city", "Switzerland"),
    ("Graz", "city", "Austria"),
    ("Hallstatt", "city", "Austria"),
    ("Innsbruck", "city", "Austria"),
    ("Linz", "city", "Austria"),
    ("Salzburg", "city", "Austria"),
    ("Dubrovnik", "city", "Croatia"),
    ("Hvar", "city", "Croatia"),
    ("Rovinj", "city", "Croatia"),
    ("Zadar", "city", "Croatia"),
    ("Zagreb", "city", "Croatia"),
    ("Pula", "city", "Croatia"),
    ("Kotor", "city", "Montenegro"),
    ("Budva", "city", "Montenegro"),
    ("Tivat", "city", "Montenegro"),
    ("Bled", "city", "Slovenia"),
    ("Piran", "city", "Slovenia"),
    ("Maribor", "city", "Slovenia"),
    ("Cesky Krumlov", "city", "Czechia"),
    ("Brno", "city", "Czechia"),
    ("Plzen", "city", "Czechia"),
    ("Pilsen", "city", "Czechia"),
    ("Bratislava", "city", "Slovakia"),
    ("Kosice", "city", "Slovakia"),
    ("Gdansk", "city", "Poland"),
    ("Poznan", "city", "Poland"),
    ("Torun", "city", "Poland"),
    ("Wroclaw", "city", "Poland"),
    ("Zakopane", "city", "Poland"),
    ("Cluj-Napoca", "city", "Romania"),
    ("Brasov", "city", "Romania"),
    ("Sibiu", "city", "Romania"),
    ("Sinaia", "city", "Romania"),
    ("Timisoara", "city", "Romania"),
    ("Ohrid", "city", "North Macedonia"),
    ("Plovdiv", "city", "Bulgaria"),
    ("Sozopol", "city", "Bulgaria"),
    ("Varna", "city", "Bulgaria"),
    ("Sarajevo", "city", "Bosnia and Herzegovina"),
    ("Mostar", "city", "Bosnia and Herzegovina"),
    ("Novi Sad", "city", "Serbia"),
    ("Tirana", "city", "Albania"),
    ("Shkoder", "city", "Albania"),
    ("Chisinau", "city", "Moldova"),
    ("Yerevan", "city", "Armenia"),
    ("Gyumri", "city", "Armenia"),
    ("Tbilisi", "city", "Georgia"),
    ("Batumi", "city", "Georgia"),
    ("Kutaisi", "city", "Georgia"),
    ("Baku", "city", "Azerbaijan"),
    ("Sheki", "city", "Azerbaijan"),
    ("Kyiv", "city", "Ukraine"),
    ("Lviv", "city", "Ukraine"),
    ("Odessa", "city", "Ukraine"),
    ("Minsk", "city", "Belarus"),
    ("Vilnius", "city", "Lithuania"),
    ("Kaunas", "city", "Lithuania"),
    ("Riga", "city", "Latvia"),
    ("Jurmala", "city", "Latvia"),
    ("Tallinn", "city", "Estonia"),
    ("Tartu", "city", "Estonia"),
    ("Helsinki", "city", "Finland"),
    ("Rovaniemi", "city", "Finland"),
    ("Turku", "city", "Finland"),
    ("Tampere", "city", "Finland"),
    ("Stockholm", "city", "Sweden"),
    ("Goteborg", "city", "Sweden"),
    ("Malmo", "city", "Sweden"),
    ("Kiruna", "city", "Sweden"),
    ("Oslo", "city", "Norway"),
    ("Bergen", "city", "Norway"),
    ("Stavanger", "city", "Norway"),
    ("Tromso", "city", "Norway"),
    ("Trondheim", "city", "Norway"),
    ("Alesund", "city", "Norway"),
    ("Copenhagen", "city", "Denmark"),
    ("Aarhus", "city", "Denmark"),
    ("Odense", "city", "Denmark"),
    ("Dublin", "city", "Ireland"),
    ("Cork", "city", "Ireland"),
    ("Galway", "city", "Ireland"),
    ("Killarney", "city", "Ireland"),
    ("Bath", "city", "United Kingdom"),
    ("Birmingham", "city", "United Kingdom"),
    ("Brighton", "city", "United Kingdom"),
    ("Bristol", "city", "United Kingdom"),
    ("Cambridge", "city", "United Kingdom"),
    ("Canterbury", "city", "United Kingdom"),
    ("Cardiff", "city", "United Kingdom"),
    ("Inverness", "city", "United Kingdom"),
    ("Liverpool", "city", "United Kingdom"),
    ("Manchester", "city", "United Kingdom"),
    ("Oxford", "city", "United Kingdom"),
    ("York", "city", "United Kingdom"),
    ("St Andrews", "city", "United Kingdom"),
    ("Fort William", "city", "United Kingdom"),
    ("Valletta", "city", "Malta"),
    ("Gozo", "city", "Malta"),
    ("Mdina", "city", "Malta"),
    ("Nicosia", "city", "Cyprus"),
    ("Limassol", "city", "Cyprus"),
    ("Paphos", "city", "Cyprus"),
    ("Reykjavik", "city", "Iceland"),
    ("Akureyri", "city", "Iceland"),

    # ── Middle East & North Africa cities ──
    ("Marrakech", "city", "Morocco"),
    ("Casablanca", "city", "Morocco"),
    ("Fes", "city", "Morocco"),
    ("Tangier", "city", "Morocco"),
    ("Essaouira", "city", "Morocco"),
    ("Agadir", "city", "Morocco"),
    ("Chefchaouen", "city", "Morocco"),
    ("Tunis", "city", "Tunisia"),
    ("Djerba", "city", "Tunisia"),
    ("Sousse", "city", "Tunisia"),
    ("Algiers", "city", "Algeria"),
    ("Luxor", "city", "Egypt"),
    ("Cairo", "city", "Egypt"),
    ("Alexandria", "city", "Egypt"),
    ("Hurghada", "city", "Egypt"),
    ("Sharm El Sheikh", "city", "Egypt"),
    ("Aswan", "city", "Egypt"),
    ("Tripoli", "city", "Libya"),
    ("Khartoum", "city", "Sudan"),
    ("Amman", "city", "Jordan"),
    ("Petra", "city", "Jordan"),
    ("Aqaba", "city", "Jordan"),
    ("Jerash", "city", "Jordan"),
    ("Beirut", "city", "Lebanon"),
    ("Byblos", "city", "Lebanon"),
    ("Baalbek", "city", "Lebanon"),
    ("Tel Aviv", "city", "Israel"),
    ("Jerusalem", "city", "Israel"),
    ("Haifa", "city", "Israel"),
    ("Eilat", "city", "Israel"),
    ("Nazareth", "city", "Israel"),
    ("Dubai", "city", "United Arab Emirates"),
    ("Abu Dhabi", "city", "United Arab Emirates"),
    ("Sharjah", "city", "United Arab Emirates"),
    ("Muscat", "city", "Oman"),
    ("Salalah", "city", "Oman"),
    ("Nizwa", "city", "Oman"),
    ("Doha", "city", "Qatar"),
    ("Manama", "city", "Bahrain"),
    ("Riyadh", "city", "Saudi Arabia"),
    ("Jeddah", "city", "Saudi Arabia"),
    ("AlUla", "city", "Saudi Arabia"),
    ("Medina", "city", "Saudi Arabia"),
    ("Mecca", "city", "Saudi Arabia"),
    ("Tabuk", "city", "Saudi Arabia"),
    ("Kuwait City", "city", "Kuwait"),
    ("Baghdad", "city", "Iraq"),
    ("Erbil", "city", "Iraq"),
    ("Tehran", "city", "Iran"),
    ("Isfahan", "city", "Iran"),
    ("Shiraz", "city", "Iran"),
    ("Yazd", "city", "Iran"),
    ("Tabriz", "city", "Iran"),
    ("Mashhad", "city", "Iran"),

    # ── Sub-Saharan Africa cities ──
    ("Nairobi", "city", "Kenya"),
    ("Mombasa", "city", "Kenya"),
    ("Lamu", "city", "Kenya"),
    ("Zanzibar City", "city", "Tanzania"),
    ("Dar es Salaam", "city", "Tanzania"),
    ("Arusha", "city", "Tanzania"),
    ("Kampala", "city", "Uganda"),
    ("Kigali", "city", "Rwanda"),
    ("Addis Ababa", "city", "Ethiopia"),
    ("Lalibela", "city", "Ethiopia"),
    ("Axum", "city", "Ethiopia"),
    ("Accra", "city", "Ghana"),
    ("Kumasi", "city", "Ghana"),
    ("Dakar", "city", "Senegal"),
    ("Saint-Louis", "city", "Senegal"),
    ("Lagos", "city", "Nigeria"),
    ("Abuja", "city", "Nigeria"),
    ("Cape Town", "city", "South Africa"),
    ("Johannesburg", "city", "South Africa"),
    ("Durban", "city", "South Africa"),
    ("Stellenbosch", "city", "South Africa"),
    ("Port Elizabeth", "city", "South Africa"),
    ("Windhoek", "city", "Namibia"),
    ("Swakopmund", "city", "Namibia"),
    ("Gaborone", "city", "Botswana"),
    ("Maun", "city", "Botswana"),
    ("Lusaka", "city", "Zambia"),
    ("Livingstone", "city", "Zambia"),
    ("Harare", "city", "Zimbabwe"),
    ("Victoria Falls", "city", "Zimbabwe"),
    ("Maputo", "city", "Mozambique"),
    ("Beira", "city", "Mozambique"),
    ("Antananarivo", "city", "Madagascar"),
    ("Nosy Be", "city", "Madagascar"),
    ("Moroni", "city", "Comoros"),
    ("Port Louis", "city", "Mauritius"),
    ("Victoria", "city", "Seychelles"),
    ("Praia", "city", "Cape Verde"),
    ("Mindelo", "city", "Cape Verde"),
    ("Abidjan", "city", "Ivory Coast"),
    ("Libreville", "city", "Gabon"),
    ("Yaounde", "city", "Cameroon"),
    ("Luanda", "city", "Angola"),

    # ── South & Central Asia cities ──
    ("Mumbai", "city", "India"),
    ("Delhi", "city", "India"),
    ("Agra", "city", "India"),
    ("Jaipur", "city", "India"),
    ("Udaipur", "city", "India"),
    ("Varanasi", "city", "India"),
    ("Chennai", "city", "India"),
    ("Goa", "city", "India"),
    ("Kochi", "city", "India"),
    ("Kolkata", "city", "India"),
    ("Bangalore", "city", "India"),
    ("Hyderabad", "city", "India"),
    ("Rishikesh", "city", "India"),
    ("McLeod Ganj", "city", "India"),
    ("Leh", "city", "India"),
    ("Manali", "city", "India"),
    ("Shimla", "city", "India"),
    ("Darjeeling", "city", "India"),
    ("Ooty", "city", "India"),
    ("Hampi", "city", "India"),
    ("Pune", "city", "India"),
    ("Ahmedabad", "city", "India"),
    ("Amritsar", "city", "India"),
    ("Kathmandu", "city", "Nepal"),
    ("Pokhara", "city", "Nepal"),
    ("Chitwan", "city", "Nepal"),
    ("Lumbini", "city", "Nepal"),
    ("Thimphu", "city", "Bhutan"),
    ("Paro", "city", "Bhutan"),
    ("Punakha", "city", "Bhutan"),
    ("Colombo", "city", "Sri Lanka"),
    ("Kandy", "city", "Sri Lanka"),
    ("Galle", "city", "Sri Lanka"),
    ("Mirissa", "city", "Sri Lanka"),
    ("Sigiriya", "city", "Sri Lanka"),
    ("Dhaka", "city", "Bangladesh"),
    ("Chittagong", "city", "Bangladesh"),
    ("Islamabad", "city", "Pakistan"),
    ("Lahore", "city", "Pakistan"),
    ("Karachi", "city", "Pakistan"),
    ("Peshawar", "city", "Pakistan"),
    ("Hunza", "city", "Pakistan"),
    ("Gilgit", "city", "Pakistan"),
    ("Kabul", "city", "Afghanistan"),
    ("Tashkent", "city", "Uzbekistan"),
    ("Samarkand", "city", "Uzbekistan"),
    ("Bukhara", "city", "Uzbekistan"),
    ("Khiva", "city", "Uzbekistan"),
    ("Bishkek", "city", "Kyrgyzstan"),
    ("Osh", "city", "Kyrgyzstan"),
    ("Karakol", "city", "Kyrgyzstan"),
    ("Dushanbe", "city", "Tajikistan"),
    ("Almaty", "city", "Kazakhstan"),
    ("Nur-Sultan", "city", "Kazakhstan"),
    ("Shymkent", "city", "Kazakhstan"),
    ("Ashgabat", "city", "Turkmenistan"),
    ("Ulaanbaatar", "city", "Mongolia"),

    # ── East & Southeast Asia cities ──
    ("Tokyo", "city", "Japan"),
    ("Osaka", "city", "Japan"),
    ("Kyoto", "city", "Japan"),
    ("Hiroshima", "city", "Japan"),
    ("Nara", "city", "Japan"),
    ("Sapporo", "city", "Japan"),
    ("Fukuoka", "city", "Japan"),
    ("Hakone", "city", "Japan"),
    ("Kanazawa", "city", "Japan"),
    ("Nikko", "city", "Japan"),
    ("Nagoya", "city", "Japan"),
    ("Sendai", "city", "Japan"),
    ("Nagasaki", "city", "Japan"),
    ("Okinawa", "city", "Japan"),
    ("Yokohama", "city", "Japan"),
    ("Kobe", "city", "Japan"),
    ("Seoul", "city", "South Korea"),
    ("Busan", "city", "South Korea"),
    ("Jeju City", "city", "South Korea"),
    ("Gyeongju", "city", "South Korea"),
    ("Incheon", "city", "South Korea"),
    ("Beijing", "city", "China"),
    ("Shanghai", "city", "China"),
    ("Chengdu", "city", "China"),
    ("Guilin", "city", "China"),
    ("Hangzhou", "city", "China"),
    ("Kunming", "city", "China"),
    ("Lhasa", "city", "China"),
    ("Lijiang", "city", "China"),
    ("Luoyang", "city", "China"),
    ("Nanjing", "city", "China"),
    ("Qingdao", "city", "China"),
    ("Suzhou", "city", "China"),
    ("Xi'an", "city", "China"),
    ("Xiamen", "city", "China"),
    ("Zhangjiajie", "city", "China"),
    ("Chongqing", "city", "China"),
    ("Sanya", "city", "China"),
    ("Hong Kong", "city", "Hong Kong"),
    ("Macau", "city", "Macau"),
    ("Taipei", "city", "Taiwan"),
    ("Tainan", "city", "Taiwan"),
    ("Taroko", "city", "Taiwan"),
    ("Kaohsiung", "city", "Taiwan"),
    ("Hualien", "city", "Taiwan"),
    ("Bangkok", "city", "Thailand"),
    ("Chiang Mai", "city", "Thailand"),
    ("Chiang Rai", "city", "Thailand"),
    ("Koh Samui", "city", "Thailand"),
    ("Krabi", "city", "Thailand"),
    ("Pattaya", "city", "Thailand"),
    ("Phuket", "city", "Thailand"),
    ("Pai", "city", "Thailand"),
    ("Ayutthaya", "city", "Thailand"),
    ("Hanoi", "city", "Vietnam"),
    ("Ho Chi Minh City", "city", "Vietnam"),
    ("Hoi An", "city", "Vietnam"),
    ("Da Nang", "city", "Vietnam"),
    ("Hue", "city", "Vietnam"),
    ("Nha Trang", "city", "Vietnam"),
    ("Sapa", "city", "Vietnam"),
    ("Dalat", "city", "Vietnam"),
    ("Phu Quoc", "city", "Vietnam"),
    ("Vung Tau", "city", "Vietnam"),
    ("Phnom Penh", "city", "Cambodia"),
    ("Siem Reap", "city", "Cambodia"),
    ("Kampot", "city", "Cambodia"),
    ("Kep", "city", "Cambodia"),
    ("Vientiane", "city", "Laos"),
    ("Luang Prabang", "city", "Laos"),
    ("Vang Vieng", "city", "Laos"),
    ("Kuala Lumpur", "city", "Malaysia"),
    ("Penang", "city", "Malaysia"),
    ("Langkawi", "city", "Malaysia"),
    ("Kota Kinabalu", "city", "Malaysia"),
    ("Malacca", "city", "Malaysia"),
    ("Ipoh", "city", "Malaysia"),
    ("Kuching", "city", "Malaysia"),
    ("Singapore", "city", "Singapore"),
    ("Yangon", "city", "Myanmar"),
    ("Bagan", "city", "Myanmar"),
    ("Mandalay", "city", "Myanmar"),
    ("Inle Lake", "city", "Myanmar"),
    ("Jakarta", "city", "Indonesia"),
    ("Bali", "city", "Indonesia"),
    ("Yogyakarta", "city", "Indonesia"),
    ("Lombok", "city", "Indonesia"),
    ("Ubud", "city", "Indonesia"),
    ("Labuan Bajo", "city", "Indonesia"),
    ("Medan", "city", "Indonesia"),
    ("Surabaya", "city", "Indonesia"),
    ("Bandung", "city", "Indonesia"),
    ("Makassar", "city", "Indonesia"),
    ("Manila", "city", "Philippines"),
    ("Cebu", "city", "Philippines"),
    ("Palawan", "city", "Philippines"),
    ("Boracay", "city", "Philippines"),
    ("Siargao", "city", "Philippines"),
    ("Davao", "city", "Philippines"),
    ("Iloilo", "city", "Philippines"),
    ("Dili", "city", "Timor-Leste"),
    ("Bandar Seri Begawan", "city", "Brunei"),
    ("Port Moresby", "city", "Papua New Guinea"),
    ("Honiara", "city", "Solomon Islands"),
    ("Port Vila", "city", "Vanuatu"),
    ("Suva", "city", "Fiji"),
    ("Nadi", "city", "Fiji"),
    ("Apia", "city", "Samoa"),
    ("Nuku'alofa", "city", "Tonga"),
    ("Papeete", "city", "French Polynesia"),
    ("Bora Bora", "city", "French Polynesia"),
    ("Moorea", "city", "French Polynesia"),
    ("Avarua", "city", "Cook Islands"),
    ("Koror", "city", "Palau"),

    # ── Americas cities ──
    ("New York City", "city", "United States"),
    ("Los Angeles", "city", "United States"),
    ("San Francisco", "city", "United States"),
    ("Chicago", "city", "United States"),
    ("Miami", "city", "United States"),
    ("Las Vegas", "city", "United States"),
    ("New Orleans", "city", "United States"),
    ("Seattle", "city", "United States"),
    ("Boston", "city", "United States"),
    ("Washington DC", "city", "United States"),
    ("Nashville", "city", "United States"),
    ("Denver", "city", "United States"),
    ("Portland", "city", "United States"),
    ("Austin", "city", "United States"),
    ("San Diego", "city", "United States"),
    ("Phoenix", "city", "United States"),
    ("Atlanta", "city", "United States"),
    ("Savannah", "city", "United States"),
    ("Charleston", "city", "United States"),
    ("Honolulu", "city", "United States"),
    ("Maui", "city", "United States"),
    ("Sedona", "city", "United States"),
    ("Santa Fe", "city", "United States"),
    ("Key West", "city", "United States"),
    ("Moab", "city", "United States"),
    ("Aspen", "city", "United States"),
    ("Jackson Hole", "city", "United States"),
    ("Napa", "city", "United States"),
    ("Toronto", "city", "Canada"),
    ("Vancouver", "city", "Canada"),
    ("Montreal", "city", "Canada"),
    ("Quebec City", "city", "Canada"),
    ("Calgary", "city", "Canada"),
    ("Ottawa", "city", "Canada"),
    ("Banff", "city", "Canada"),
    ("Jasper", "city", "Canada"),
    ("Victoria", "city", "Canada"),
    ("Whistler", "city", "Canada"),
    ("Whitehorse", "city", "Canada"),
    ("Yellowknife", "city", "Canada"),
    ("Mexico City", "city", "Mexico"),
    ("Cancun", "city", "Mexico"),
    ("Playa del Carmen", "city", "Mexico"),
    ("Tulum", "city", "Mexico"),
    ("Oaxaca", "city", "Mexico"),
    ("Guadalajara", "city", "Mexico"),
    ("San Miguel de Allende", "city", "Mexico"),
    ("Merida", "city", "Mexico"),
    ("Guanajuato", "city", "Mexico"),
    ("Puerto Vallarta", "city", "Mexico"),
    ("Los Cabos", "city", "Mexico"),
    ("Monterrey", "city", "Mexico"),
    ("Taxco", "city", "Mexico"),
    ("Havana", "city", "Cuba"),
    ("Trinidad", "city", "Cuba"),
    ("Kingston", "city", "Jamaica"),
    ("Nassau", "city", "Bahamas"),
    ("Bridgetown", "city", "Barbados"),
    ("Castries", "city", "Saint Lucia"),
    ("Willemstad", "city", "Curacao"),
    ("Oranjestad", "city", "Aruba"),
    ("St. George's", "city", "Grenada"),
    ("Montego Bay", "city", "Jamaica"),
    ("Punta Cana", "city", "Dominican Republic"),
    ("Santo Domingo", "city", "Dominican Republic"),
    ("San Juan", "city", "Puerto Rico"),
    ("Port of Spain", "city", "Trinidad and Tobago"),
    ("Guatemala City", "city", "Guatemala"),
    ("Antigua Guatemala", "city", "Guatemala"),
    ("Flores", "city", "Guatemala"),
    ("Belize City", "city", "Belize"),
    ("San Pedro", "city", "Belize"),
    ("San Jose", "city", "Costa Rica"),
    ("Manuel Antonio", "city", "Costa Rica"),
    ("La Fortuna", "city", "Costa Rica"),
    ("Panama City", "city", "Panama"),
    ("Bocas del Toro", "city", "Panama"),
    ("Bogota", "city", "Colombia"),
    ("Medellin", "city", "Colombia"),
    ("Cartagena", "city", "Colombia"),
    ("Cali", "city", "Colombia"),
    ("Santa Marta", "city", "Colombia"),
    ("Lima", "city", "Peru"),
    ("Cusco", "city", "Peru"),
    ("Arequipa", "city", "Peru"),
    ("Machu Picchu", "city", "Peru"),
    ("Iquitos", "city", "Peru"),
    ("Puno", "city", "Peru"),
    ("Buenos Aires", "city", "Argentina"),
    ("Mendoza", "city", "Argentina"),
    ("Bariloche", "city", "Argentina"),
    ("El Calafate", "city", "Argentina"),
    ("Salta", "city", "Argentina"),
    ("Mar del Plata", "city", "Argentina"),
    ("Cordoba", "city", "Argentina"),
    ("Iguazu Falls", "city", "Argentina"),
    ("Santiago", "city", "Chile"),
    ("Valparaiso", "city", "Chile"),
    ("San Pedro de Atacama", "city", "Chile"),
    ("Puerto Natales", "city", "Chile"),
    ("Pucón", "city", "Chile"),
    ("Vina del Mar", "city", "Chile"),
    ("Sao Paulo", "city", "Brazil"),
    ("Rio de Janeiro", "city", "Brazil"),
    ("Salvador", "city", "Brazil"),
    ("Florianopolis", "city", "Brazil"),
    ("Manaus", "city", "Brazil"),
    ("Recife", "city", "Brazil"),
    ("Natal", "city", "Brazil"),
    ("Foz do Iguacu", "city", "Brazil"),
    ("Montevideo", "city", "Uruguay"),
    ("Punta del Este", "city", "Uruguay"),
    ("Quito", "city", "Ecuador"),
    ("Galapagos Islands", "city", "Ecuador"),
    ("Banos", "city", "Ecuador"),
    ("Cuenca", "city", "Ecuador"),
    ("La Paz", "city", "Bolivia"),
    ("Uyuni", "city", "Bolivia"),
    ("Sucre", "city", "Bolivia"),
    ("Copacabana", "city", "Bolivia"),
    ("Asuncion", "city", "Paraguay"),
    ("Paramaribo", "city", "Suriname"),

    # ── Oceania cities ──
    ("Sydney", "city", "Australia"),
    ("Melbourne", "city", "Australia"),
    ("Brisbane", "city", "Australia"),
    ("Perth", "city", "Australia"),
    ("Adelaide", "city", "Australia"),
    ("Cairns", "city", "Australia"),
    ("Gold Coast", "city", "Australia"),
    ("Darwin", "city", "Australia"),
    ("Hobart", "city", "Australia"),
    ("Uluru", "city", "Australia"),
    ("Alice Springs", "city", "Australia"),
    ("Byron Bay", "city", "Australia"),
    ("Broome", "city", "Australia"),
    ("Auckland", "city", "New Zealand"),
    ("Wellington", "city", "New Zealand"),
    ("Queenstown", "city", "New Zealand"),
    ("Christchurch", "city", "New Zealand"),
    ("Rotorua", "city", "New Zealand"),
    ("Taupo", "city", "New Zealand"),
    ("Napier", "city", "New Zealand"),
    ("Nelson", "city", "New Zealand"),
    ("Wanaka", "city", "New Zealand"),
    ("Dunedin", "city", "New Zealand"),

    # ── European regions ──
    ("Amalfi Coast", "region", "Italy"),
    ("Cinque Terre", "region", "Italy"),
    ("Tuscany", "region", "Italy"),
    ("Puglia", "region", "Italy"),
    ("Sicily", "region", "Italy"),
    ("Sardinia", "region", "Italy"),
    ("Dolomites", "region", "Italy"),
    ("Lake Como", "region", "Italy"),
    ("Lake Garda", "region", "Italy"),
    ("South Tyrol", "region", "Italy"),
    ("Abruzzo", "region", "Italy"),
    ("Basilicata", "region", "Italy"),
    ("Calabria", "region", "Italy"),
    ("Campania Coast", "region", "Italy"),
    ("Chianti", "region", "Italy"),
    ("Emilia-Romagna", "region", "Italy"),
    ("Friuli", "region", "Italy"),
    ("Umbria", "region", "Italy"),
    ("Val d'Aosta", "region", "Italy"),
    ("Algarve", "region", "Portugal"),
    ("Madeira", "region", "Portugal"),
    ("Azores", "region", "Portugal"),
    ("Douro Valley", "region", "Portugal"),
    ("Alentejo", "region", "Portugal"),
    ("Costa Vicentina", "region", "Portugal"),
    ("Minho", "region", "Portugal"),
    ("Serra da Estrela", "region", "Portugal"),
    ("Andalusia", "region", "Spain"),
    ("Balearic Islands", "region", "Spain"),
    ("Canary Islands", "region", "Spain"),
    ("Mallorca", "region", "Spain"),
    ("Ibiza", "region", "Spain"),
    ("Menorca", "region", "Spain"),
    ("Tenerife", "region", "Spain"),
    ("Lanzarote", "region", "Spain"),
    ("Fuerteventura", "region", "Spain"),
    ("Catalonia", "region", "Spain"),
    ("Basque Country", "region", "Spain"),
    ("Costa Brava", "region", "Spain"),
    ("Costa del Sol", "region", "Spain"),
    ("Galicia", "region", "Spain"),
    ("Valencia Region", "region", "Spain"),
    ("La Rioja", "region", "Spain"),
    ("Navarra", "region", "Spain"),
    ("Aragon Pyrenees", "region", "Spain"),
    ("Sierra Nevada", "region", "Spain"),
    ("Provence", "region", "France"),
    ("French Riviera", "region", "France"),
    ("Dordogne", "region", "France"),
    ("Normandy", "region", "France"),
    ("Brittany", "region", "France"),
    ("Loire Valley", "region", "France"),
    ("Bordeaux Wine Region", "region", "France"),
    ("Burgundy", "region", "France"),
    ("Alsace", "region", "France"),
    ("Corsica", "region", "France"),
    ("French Alps", "region", "France"),
    ("Mont Blanc Region", "region", "France"),
    ("Pyrenees France", "region", "France"),
    ("Languedoc", "region", "France"),
    ("Champagne Region", "region", "France"),
    ("Perigord", "region", "France"),
    ("Swiss Alps", "region", "Switzerland"),
    ("Bernese Oberland", "region", "Switzerland"),
    ("Jungfrau Region", "region", "Switzerland"),
    ("Zermatt Region", "region", "Switzerland"),
    ("Engadin", "region", "Switzerland"),
    ("Lake Geneva Region", "region", "Switzerland"),
    ("Ticino", "region", "Switzerland"),
    ("Lucerne Region", "region", "Switzerland"),
    ("Bavarian Alps", "region", "Germany"),
    ("Black Forest", "region", "Germany"),
    ("Rhine Valley", "region", "Germany"),
    ("Mosel Valley", "region", "Germany"),
    ("Bavarian Lake District", "region", "Germany"),
    ("Romantic Road", "region", "Germany"),
    ("Rugen Island", "region", "Germany"),
    ("Harz Mountains", "region", "Germany"),
    ("Saxon Switzerland", "region", "Germany"),
    ("Lake Constance", "region", "Germany"),
    ("Tyrol", "region", "Austria"),
    ("Salzkammergut", "region", "Austria"),
    ("Vorarlberg", "region", "Austria"),
    ("Styria", "region", "Austria"),
    ("Carinthia Lakes", "region", "Austria"),
    ("Innviertel", "region", "Austria"),
    ("Scottish Highlands", "region", "United Kingdom"),
    ("Lake District", "region", "United Kingdom"),
    ("Cotswolds", "region", "United Kingdom"),
    ("Cornish Coast", "region", "United Kingdom"),
    ("Snowdonia", "region", "United Kingdom"),
    ("Peak District", "region", "United Kingdom"),
    ("Yorkshire Dales", "region", "United Kingdom"),
    ("Isle of Skye", "region", "United Kingdom"),
    ("Outer Hebrides", "region", "United Kingdom"),
    ("Pembrokeshire Coast", "region", "United Kingdom"),
    ("Brecon Beacons", "region", "United Kingdom"),
    ("New Forest", "region", "United Kingdom"),
    ("South Downs", "region", "United Kingdom"),
    ("Dartmoor", "region", "United Kingdom"),
    ("Exmoor", "region", "United Kingdom"),
    ("Dalmatian Coast", "region", "Croatia"),
    ("Istria", "region", "Croatia"),
    ("Plitvice Lakes", "region", "Croatia"),
    ("Kvarner Gulf", "region", "Croatia"),
    ("Hvar Island", "region", "Croatia"),
    ("Brac Island", "region", "Croatia"),
    ("Korcula Island", "region", "Croatia"),
    ("Slovene Alps", "region", "Slovenia"),
    ("Julian Alps", "region", "Slovenia"),
    ("Triglav National Park", "region", "Slovenia"),
    ("Lake Bled Region", "region", "Slovenia"),
    ("Karst Region", "region", "Slovenia"),
    ("Sooca Valley", "region", "Slovenia"),
    ("Montenegro Coast", "region", "Montenegro"),
    ("Durmitor", "region", "Montenegro"),
    ("Bay of Kotor", "region", "Montenegro"),
    ("Albanian Riviera", "region", "Albania"),
    ("Accursed Mountains", "region", "Albania"),
    ("Crete", "region", "Greece"),
    ("Santorini", "region", "Greece"),
    ("Mykonos", "region", "Greece"),
    ("Corfu", "region", "Greece"),
    ("Rhodes", "region", "Greece"),
    ("Cyclades", "region", "Greece"),
    ("Ionian Islands", "region", "Greece"),
    ("Dodecanese", "region", "Greece"),
    ("Meteora", "region", "Greece"),
    ("Peloponnese", "region", "Greece"),
    ("Epirus Mountains", "region", "Greece"),
    ("Zakynthos", "region", "Greece"),
    ("Kefalonia", "region", "Greece"),
    ("Lesbos", "region", "Greece"),
    ("Samos", "region", "Greece"),
    ("Chios", "region", "Greece"),
    ("Mosel Wine Region", "region", "Germany"),
    ("Lofoten Islands", "region", "Norway"),
    ("Fjordland Norway", "region", "Norway"),
    ("Nordfjord", "region", "Norway"),
    ("Sognefjord", "region", "Norway"),
    ("Hardangerfjord", "region", "Norway"),
    ("Svalbard", "region", "Norway"),
    ("Telemark", "region", "Norway"),
    ("Vesteralen", "region", "Norway"),
    ("Faroe Islands", "region", "Denmark"),
    ("Bornholm", "region", "Denmark"),
    ("Swedish Lapland", "region", "Sweden"),
    ("Gothenburg Archipelago", "region", "Sweden"),
    ("Stockholm Archipelago", "region", "Sweden"),
    ("Dalarna", "region", "Sweden"),
    ("Gotland", "region", "Sweden"),
    ("Finnish Lakeland", "region", "Finland"),
    ("Lapland Finland", "region", "Finland"),
    ("Aland Islands", "region", "Finland"),
    ("Bohemia", "region", "Czechia"),
    ("Moravian Wine Region", "region", "Czechia"),
    ("Bohemian Switzerland", "region", "Czechia"),
    ("Tatra Mountains Slovakia", "region", "Slovakia"),
    ("Tatras", "region", "Poland"),
    ("Mazury Lakes", "region", "Poland"),
    ("Bieszczady", "region", "Poland"),
    ("Kashubia", "region", "Poland"),
    ("Carpathians Romania", "region", "Romania"),
    ("Transylvania", "region", "Romania"),
    ("Danube Delta", "region", "Romania"),
    ("Maramures", "region", "Romania"),
    ("Bulgarian Black Sea Coast", "region", "Bulgaria"),
    ("Rhodope Mountains", "region", "Bulgaria"),
    ("Rila Mountains", "region", "Bulgaria"),
    ("Bosnian Alps", "region", "Bosnia and Herzegovina"),
    ("Serbian Monasteries", "region", "Serbia"),
    ("Ohrid Region", "region", "North Macedonia"),
    ("Baltic Coast Lithuania", "region", "Lithuania"),
    ("Curonian Spit", "region", "Lithuania"),
    ("Gauja Valley", "region", "Latvia"),
    ("Saaremaa", "region", "Estonia"),
    ("Caucasus Georgia", "region", "Georgia"),
    ("Kazbegi Region", "region", "Georgia"),
    ("Svaneti", "region", "Georgia"),
    ("Tuscany Coast", "region", "Italy"),

    # ── Middle East regions ──
    ("Cappadocia", "region", "Turkey"),
    ("Turquoise Coast", "region", "Turkey"),
    ("Aegean Coast Turkey", "region", "Turkey"),
    ("Bodrum Peninsula", "region", "Turkey"),
    ("Pamukkale Region", "region", "Turkey"),
    ("Istanbul Region", "region", "Turkey"),
    ("Kaçkar Mountains", "region", "Turkey"),
    ("Lycia", "region", "Turkey"),
    ("Wadi Rum", "region", "Jordan"),
    ("Dead Sea Region", "region", "Jordan"),
    ("Petra Region", "region", "Jordan"),
    ("Aqaba Coast", "region", "Jordan"),
    ("Sinai Coast", "region", "Egypt"),
    ("Nile Valley", "region", "Egypt"),
    ("Red Sea Riviera", "region", "Egypt"),
    ("Atlas Mountains", "region", "Morocco"),
    ("Sahara Morocco", "region", "Morocco"),
    ("Essaouira Coast", "region", "Morocco"),
    ("Al Ula Region", "region", "Saudi Arabia"),
    ("Asir Mountains", "region", "Saudi Arabia"),
    ("Hadhramaut", "region", "Yemen"),
    ("Musandam", "region", "Oman"),
    ("Oman Coast", "region", "Oman"),
    ("Dhofar", "region", "Oman"),
    ("Hajar Mountains", "region", "Oman"),
    ("Abu Dhabi Coast", "region", "United Arab Emirates"),

    # ── Africa regions ──
    ("Masai Mara", "region", "Kenya"),
    ("Amboseli", "region", "Kenya"),
    ("Diani Beach", "region", "Kenya"),
    ("Mount Kenya Region", "region", "Kenya"),
    ("Serengeti", "region", "Tanzania"),
    ("Zanzibar Island", "region", "Tanzania"),
    ("Ngorongoro", "region", "Tanzania"),
    ("Kilimanjaro Region", "region", "Tanzania"),
    ("Ruaha", "region", "Tanzania"),
    ("Okavango Delta", "region", "Botswana"),
    ("Chobe", "region", "Botswana"),
    ("Makgadikgadi Pans", "region", "Botswana"),
    ("Kruger Region", "region", "South Africa"),
    ("Garden Route", "region", "South Africa"),
    ("Cape Winelands", "region", "South Africa"),
    ("Table Mountain Region", "region", "South Africa"),
    ("Drakensberg", "region", "South Africa"),
    ("Western Cape", "region", "South Africa"),
    ("iSimangaliso", "region", "South Africa"),
    ("Victoria Falls Region", "region", "Zimbabwe"),
    ("Hwange", "region", "Zimbabwe"),
    ("Luangwa Valley", "region", "Zambia"),
    ("South Luangwa", "region", "Zambia"),
    ("Volcanoes National Park", "region", "Rwanda"),
    ("Bwindi", "region", "Uganda"),
    ("Queen Elizabeth Park", "region", "Uganda"),
    ("Namib Desert", "region", "Namibia"),
    ("Etosha", "region", "Namibia"),
    ("Skeleton Coast", "region", "Namibia"),
    ("Sahara Desert", "region", "Algeria"),
    ("Atlas Mountains Algeria", "region", "Algeria"),
    ("Nosy Be Island", "region", "Madagascar"),
    ("Tsingy de Bemaraha", "region", "Madagascar"),
    ("Seychelles Inner Islands", "region", "Seychelles"),
    ("Mauritius East Coast", "region", "Mauritius"),
    ("Reunion Island Highlands", "region", "Reunion"),
    ("Cape Verde Sal", "region", "Cape Verde"),
    ("Fernando de Noronha", "region", "Brazil"),

    # ── South & Central Asia regions ──
    ("Rajasthan", "region", "India"),
    ("Kerala", "region", "India"),
    ("Goa Coast", "region", "India"),
    ("Ladakh", "region", "India"),
    ("Himachal Pradesh", "region", "India"),
    ("Uttarakhand Himalayas", "region", "India"),
    ("Andaman Islands", "region", "India"),
    ("Lakshadweep", "region", "India"),
    ("Coorg", "region", "India"),
    ("Spiti Valley", "region", "India"),
    ("Munnar", "region", "India"),
    ("Sundarbans", "region", "India"),
    ("Jim Corbett", "region", "India"),
    ("Ranthambore", "region", "India"),
    ("Annapurna Region", "region", "Nepal"),
    ("Everest Region", "region", "Nepal"),
    ("Kathmandu Valley", "region", "Nepal"),
    ("Mustang", "region", "Nepal"),
    ("Chitwan", "region", "Nepal"),
    ("Punakha Valley", "region", "Bhutan"),
    ("Paro Valley", "region", "Bhutan"),
    ("Cultural Triangle Sri Lanka", "region", "Sri Lanka"),
    ("South Coast Sri Lanka", "region", "Sri Lanka"),
    ("Hill Country Sri Lanka", "region", "Sri Lanka"),
    ("Silk Road Uzbekistan", "region", "Uzbekistan"),
    ("Pamir Highway", "region", "Tajikistan"),
    ("Wakhan Corridor", "region", "Tajikistan"),
    ("Issyk-Kul Lake", "region", "Kyrgyzstan"),
    ("Tian Shan Mountains", "region", "Kyrgyzstan"),
    ("Altai Mountains", "region", "Kazakhstan"),
    ("Charyn Canyon", "region", "Kazakhstan"),

    # ── East Asia regions ──
    ("Hokkaido", "region", "Japan"),
    ("Okinawa", "region", "Japan"),
    ("Kansai", "region", "Japan"),
    ("Kyoto Prefecture", "region", "Japan"),
    ("Tokyo Region", "region", "Japan"),
    ("Japanese Alps", "region", "Japan"),
    ("Fuji Five Lakes", "region", "Japan"),
    ("Hakone Region", "region", "Japan"),
    ("Nikko Region", "region", "Japan"),
    ("Kumano Kodo", "region", "Japan"),
    ("Shikoku", "region", "Japan"),
    ("Jeju Island", "region", "South Korea"),
    ("Gyeongju Region", "region", "South Korea"),
    ("Jirisan National Park", "region", "South Korea"),
    ("Yellow Sea Coast Korea", "region", "South Korea"),
    ("Guilin Karst", "region", "China"),
    ("Zhangjiajie Park", "region", "China"),
    ("Yunnan Province", "region", "China"),
    ("Sichuan Mountains", "region", "China"),
    ("Tibet Plateau", "region", "China"),
    ("Li River Valley", "region", "China"),
    ("Yangshuo", "region", "China"),
    ("Xinjiang", "region", "China"),
    ("Hainan Island", "region", "China"),
    ("Three Gorges", "region", "China"),

    # ── Southeast Asia regions ──
    ("Bali", "region", "Indonesia"),
    ("Bali Highlands", "region", "Indonesia"),
    ("Komodo Region", "region", "Indonesia"),
    ("Raja Ampat", "region", "Indonesia"),
    ("Lombok", "region", "Indonesia"),
    ("Gili Islands", "region", "Indonesia"),
    ("Borneo Sabah", "region", "Malaysia"),
    ("Cameron Highlands", "region", "Malaysia"),
    ("Langkawi Island", "region", "Malaysia"),
    ("Penang Island", "region", "Malaysia"),
    ("Ha Long Bay", "region", "Vietnam"),
    ("Sapa Region", "region", "Vietnam"),
    ("Mekong Delta", "region", "Vietnam"),
    ("Hoi An Coast", "region", "Vietnam"),
    ("Central Vietnam Coast", "region", "Vietnam"),
    ("Phi Phi Islands", "region", "Thailand"),
    ("Koh Samui Island", "region", "Thailand"),
    ("Krabi Coast", "region", "Thailand"),
    ("Phuket Island", "region", "Thailand"),
    ("Chiang Mai Highlands", "region", "Thailand"),
    ("Khao Yai", "region", "Thailand"),
    ("Angkor Region", "region", "Cambodia"),
    ("Luang Prabang Region", "region", "Laos"),
    ("Palau Rock Islands", "region", "Palau"),
    ("Ambergris Caye", "region", "Belize"),
    ("Bocas del Toro Archipelago", "region", "Panama"),

    # ── Oceania regions ──
    ("Great Barrier Reef", "region", "Australia"),
    ("Whitsundays", "region", "Australia"),
    ("Daintree Rainforest", "region", "Australia"),
    ("Kimberley", "region", "Australia"),
    ("Barossa Valley", "region", "Australia"),
    ("Blue Mountains", "region", "Australia"),
    ("Hunter Valley", "region", "Australia"),
    ("Flinders Ranges", "region", "Australia"),
    ("Red Centre", "region", "Australia"),
    ("Great Ocean Road", "region", "Australia"),
    ("Tasmania Wilderness", "region", "Australia"),
    ("Kangaroo Island", "region", "Australia"),
    ("South Island New Zealand", "region", "New Zealand"),
    ("Fiordland", "region", "New Zealand"),
    ("Queenstown Lakes", "region", "New Zealand"),
    ("Rotorua Lakes", "region", "New Zealand"),
    ("Bay of Islands", "region", "New Zealand"),
    ("Coromandel Peninsula", "region", "New Zealand"),
    ("Abel Tasman", "region", "New Zealand"),
    ("Arthur's Pass", "region", "New Zealand"),
    ("Kaikoura Coast", "region", "New Zealand"),
    ("Bora Bora", "region", "French Polynesia"),
    ("Moorea", "region", "French Polynesia"),
    ("Tahiti", "region", "French Polynesia"),
    ("Yasawa Islands", "region", "Fiji"),
    ("Rarotonga", "region", "Cook Islands"),

    # ── North & Central America regions ──
    ("Banff National Park", "region", "Canada"),
    ("Canadian Rockies", "region", "Canada"),
    ("Jasper National Park", "region", "Canada"),
    ("Vancouver Island", "region", "Canada"),
    ("Quebec Charlevoix", "region", "Canada"),
    ("Niagara Region", "region", "Canada"),
    ("Cape Breton", "region", "Canada"),
    ("Yukon", "region", "Canada"),
    ("Grand Canyon", "region", "United States"),
    ("Yellowstone Region", "region", "United States"),
    ("Yosemite Region", "region", "United States"),
    ("Rocky Mountain Park", "region", "United States"),
    ("Glacier National Park", "region", "United States"),
    ("Zion National Park", "region", "United States"),
    ("Bryce Canyon", "region", "United States"),
    ("Arches National Park", "region", "United States"),
    ("Acadia National Park", "region", "United States"),
    ("Great Smoky Mountains", "region", "United States"),
    ("Big Sur", "region", "United States"),
    ("California Wine Country", "region", "United States"),
    ("Florida Keys", "region", "United States"),
    ("Hawaii Big Island", "region", "United States"),
    ("Hawaii Maui", "region", "United States"),
    ("Hawaii Kauai", "region", "United States"),
    ("Utah Parks Region", "region", "United States"),
    ("Riviera Maya", "region", "Mexico"),
    ("Yucatan Peninsula", "region", "Mexico"),
    ("Copper Canyon", "region", "Mexico"),
    ("Baja California Sur", "region", "Mexico"),
    ("Oaxaca Coast", "region", "Mexico"),
    ("Guanajuato Region", "region", "Mexico"),
    ("Lake Atitlan", "region", "Guatemala"),
    ("Tikal Region", "region", "Guatemala"),
    ("Costa Rica Arenal", "region", "Costa Rica"),
    ("Nicoya Peninsula", "region", "Costa Rica"),
    ("Manuel Antonio Region", "region", "Costa Rica"),
    ("Guanacaste", "region", "Costa Rica"),
    ("Bocas del Toro", "region", "Panama"),

    # ── South America regions ──
    ("Patagonia", "region", "Argentina"),
    ("Iguazu Region", "region", "Argentina"),
    ("Mendoza Wine Region", "region", "Argentina"),
    ("Atacama Desert", "region", "Chile"),
    ("Torres del Paine", "region", "Chile"),
    ("Carretera Austral", "region", "Chile"),
    ("Chiloe Island", "region", "Chile"),
    ("Lake District Chile", "region", "Chile"),
    ("Amazon Brazil", "region", "Brazil"),
    ("Pantanal", "region", "Brazil"),
    ("Chapada Diamantina", "region", "Brazil"),
    ("Lencois Maranhenses", "region", "Brazil"),
    ("Serra Gaucha", "region", "Brazil"),
    ("Galapagos Islands", "region", "Ecuador"),
    ("Amazon Ecuador", "region", "Ecuador"),
    ("Sacred Valley Peru", "region", "Peru"),
    ("Colca Canyon", "region", "Peru"),
    ("Amazon Peru", "region", "Peru"),
    ("Lake Titicaca", "region", "Peru"),
    ("Salar de Uyuni", "region", "Bolivia"),
    ("Amazon Bolivia", "region", "Bolivia"),
    ("Altiplano", "region", "Bolivia"),
    ("Coffee Region Colombia", "region", "Colombia"),
    ("Caribbean Coast Colombia", "region", "Colombia"),
    ("Cartagena Coast", "region", "Colombia"),
    ("Tayrona Park", "region", "Colombia"),
    ("Pantanal Bolivia", "region", "Bolivia"),
    ("Caroni Swamp", "region", "Trinidad and Tobago"),
    ("Tobago Coast", "region", "Trinidad and Tobago"),

    # ── Ski resorts / mountain areas ──
    ("Verbier", "region", "Switzerland"),
    ("Val Thorens", "region", "France"),
    ("Courchevel", "region", "France"),
    ("Meribel", "region", "France"),
    ("Val d'Isere", "region", "France"),
    ("Megeve", "region", "France"),
    ("Les Gets", "region", "France"),
    ("Morzine", "region", "France"),
    ("Tignes", "region", "France"),
    ("Alpe d'Huez", "region", "France"),
    ("Kitzbuhel", "region", "Austria"),
    ("St Anton", "region", "Austria"),
    ("Lech", "region", "Austria"),
    ("Ischgl", "region", "Austria"),
    ("Saalbach", "region", "Austria"),
    ("Bad Gastein", "region", "Austria"),
    ("Davos", "region", "Switzerland"),
    ("Wengen", "region", "Switzerland"),
    ("Saas-Fee", "region", "Switzerland"),
    ("Andermatt", "region", "Switzerland"),
    ("Grindelwald", "region", "Switzerland"),
    ("Cortina d'Ampezzo", "region", "Italy"),
    ("Val Gardena", "region", "Italy"),
    ("Livigno", "region", "Italy"),
    ("Madonna di Campiglio", "region", "Italy"),
    ("Garmisch-Partenkirchen", "region", "Germany"),
    ("Berchtesgaden", "region", "Germany"),
    ("Bansko", "region", "Bulgaria"),
    ("Jasna", "region", "Slovakia"),
    ("Kasprowy Wierch", "region", "Poland"),
    ("Whistler Blackcomb", "region", "Canada"),
    ("Vail", "region", "United States"),
    ("Park City", "region", "United States"),
    ("Breckenridge", "region", "United States"),
    ("Steamboat Springs", "region", "United States"),
    ("Lake Tahoe", "region", "United States"),
    ("Mammoth Mountain", "region", "United States"),
    ("Hakuba", "region", "Japan"),
    ("Niseko", "region", "Japan"),
    ("Queenstown Ski Region", "region", "New Zealand"),

    # ── Wine regions ──
    ("Champagne", "region", "France"),
    ("Burgundy Wine Region", "region", "France"),
    ("Rhone Valley", "region", "France"),
    ("Languedoc-Roussillon", "region", "France"),
    ("Barossa Valley Wine", "region", "Australia"),
    ("Marlborough Wine Region", "region", "New Zealand"),
    ("Napa Valley", "region", "United States"),
    ("Sonoma Valley", "region", "United States"),
    ("Willamette Valley", "region", "United States"),
    ("Rioja Wine Region", "region", "Spain"),
    ("Priorat", "region", "Spain"),
    ("Ribera del Duero", "region", "Spain"),
    ("Penedes", "region", "Spain"),
    ("Vinho Verde", "region", "Portugal"),
    ("Alentejo Wine", "region", "Portugal"),
    ("Chianti Classico", "region", "Italy"),
    ("Barolo Region", "region", "Italy"),
    ("Prosecco Hills", "region", "Italy"),
    ("Mosel Wine", "region", "Germany"),
    ("Rhine Wine Region", "region", "Germany"),
    ("Mendoza Wine", "region", "Argentina"),
    ("Colchagua Valley", "region", "Chile"),
    ("Casablanca Valley", "region", "Chile"),
    ("Cape Winelands SA", "region", "South Africa"),
    ("Hunter Valley Wine", "region", "Australia"),
    ("Yarra Valley", "region", "Australia"),
    ("Margaret River", "region", "Australia"),
    ("Wachau", "region", "Austria"),
    ("Tokaj", "region", "Hungary"),
    ("Georgia Wine Region", "region", "Georgia"),
    ("Bekaa Valley", "region", "Lebanon"),
    ("Santorini Wine", "region", "Greece"),
    ("Priorat Wine", "region", "Spain"),
]

# ── Main generation ───────────────────────────────────────────────────────────

def main():
    # Load spreadsheet entries
    wb = openpyxl.load_workbook(str(XLSX))
    ws = wb.active
    headers = [cell.value for cell in ws[1]]
    entries: list[tuple[str, str, str]] = []  # (name, type, country)

    for row in ws.iter_rows(min_row=2, values_only=True):
        d = dict(zip(headers, row))
        if not d.get("name"):
            continue
        dest_type = d.get("destination_type", "region")
        # Skip generated fill entries (not real places)
        if d.get("season_tags") == "generated-fill":
            continue
        country = d.get("country_name") or ""
        entries.append((str(d["name"]), str(dest_type), str(country)))

    # Add extra entries
    # Avoid duplicates by name (case-insensitive)
    seen_names: set[str] = {e[0].lower() for e in entries}
    for name, dtype, country in EXTRA_ENTRIES:
        if name.lower() not in seen_names:
            entries.append((name, dtype, country))
            seen_names.add(name.lower())

    print(f"Total entries: {len(entries)}")

    # Build LOCATION_TAGS
    tags_map: dict[str, list[str]] = {}
    for name, dtype, country in entries:
        tags = infer_tags(name, dtype, country)
        tags_map[name] = tags

    # Build ALL_LOCATIONS (sorted)
    all_locations = sorted({e[0] for e in entries})
    print(f"ALL_LOCATIONS count: {len(all_locations)}")

    # ── Write TypeScript ──────────────────────────────────────────────────────
    lines: list[str] = []
    lines.append("// Auto-generated by scripts/gen_location_data.py — do not edit by hand")
    lines.append("")
    lines.append("export type GeoTag =")
    lines.append('  | "beach" | "mountain" | "city" | "countryside" | "tropical"')
    lines.append('  | "arctic" | "desert" | "island" | "lake" | "forest";')
    lines.append("")

    # DESTINATION_LIST
    destinations = [
        "Beach & Coast", "Mountains & Highlands", "Countryside & Rural", "City & Culture",
        "Lakes & Rivers", "Forest & Nature", "Islands", "Desert & Arid", "Snow & Ice", "Jungle & Tropics",
    ]
    lines.append("export const DESTINATION_LIST: string[] = [")
    for d in destinations:
        lines.append(f'  "{d}",')
    lines.append("];")
    lines.append("")

    # DESTINATION_GEO_TAGS
    lines.append("export const DESTINATION_GEO_TAGS: Record<string, GeoTag[]> = {")
    dest_geo = {
        "Beach & Coast":         ["beach", "island", "tropical"],
        "Mountains & Highlands": ["mountain", "arctic"],
        "Countryside & Rural":   ["countryside", "forest"],
        "City & Culture":        ["city"],
        "Lakes & Rivers":        ["lake", "mountain", "countryside"],
        "Forest & Nature":       ["forest", "mountain", "countryside", "tropical"],
        "Islands":               ["island", "beach", "tropical"],
        "Desert & Arid":         ["desert"],
        "Snow & Ice":            ["arctic", "mountain"],
        "Jungle & Tropics":      ["tropical"],
    }
    for dest, tags in dest_geo.items():
        tag_str = ", ".join(f'"{t}"' for t in tags)
        lines.append(f'  "{dest}": [{tag_str}],')
    lines.append("};")
    lines.append("")

    # ALL_LOCATIONS
    lines.append("export const ALL_LOCATIONS: string[] = [")
    for loc in all_locations:
        escaped = loc.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'  "{escaped}",')
    lines.append("];")
    lines.append("")

    # LOCATION_TAGS
    lines.append("export const LOCATION_TAGS: Partial<Record<string, GeoTag[]>> = {")
    for loc in all_locations:
        tags = tags_map.get(loc, [])
        if tags:
            tag_str = ", ".join(f'"{t}"' for t in tags)
            escaped = loc.replace("\\", "\\\\").replace('"', '\\"')
            lines.append(f'  "{escaped}": [{tag_str}],')
    lines.append("};")
    lines.append("")

    # getAvailableDestinations — placed after LOCATION_TAGS to avoid forward-reference
    lines.append("export function getAvailableDestinations(selectedLocations: string[]): string[] {")
    lines.append("  if (selectedLocations.length === 0) return DESTINATION_LIST;")
    lines.append("  const geoTags = new Set<GeoTag>();")
    lines.append("  for (const loc of selectedLocations) {")
    lines.append("    const tags = LOCATION_TAGS[loc];")
    lines.append("    if (!tags) return DESTINATION_LIST;")
    lines.append("    tags.forEach((t) => geoTags.add(t));")
    lines.append("  }")
    lines.append("  return DESTINATION_LIST.filter((dest) => {")
    lines.append("    const destTags = DESTINATION_GEO_TAGS[dest] ?? [];")
    lines.append("    return destTags.some((t) => geoTags.has(t));")
    lines.append("  });")
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {OUT}")

if __name__ == "__main__":
    main()